<?php
if ( ! isset( $data['order_id'] ) ) {
	return;
}

use Omnipay\Omnipay;

$merchantId        = get_option( 'mobilpay_merchantid', 'payments' );
$publicCertificate = json_decode( get_option( 'mobilpay_public_certificate', 'payments' ) );
$privateKey        = json_decode( get_option( 'mobilpay_private_key', 'payments' ) );
$testMode          = get_option( 'mobilpay_testmode', 'payments' ) == 1 ? true : false;

$gateway = Omnipay::create( 'MobilPay' );
$gateway->setMerchantId( $merchantId );
$gateway->setPrivateKey( $privateKey->path );

$response = $gateway->completePurchase( $_POST )->send();

switch ( $response->getMessage() ) {
	case 'confirmed_pending': // transaction is pending review. After this is done, a new IPN request will be sent with either confirmation or cancellation
	case 'paid_pending': // transaction is pending review. After this is done, a new IPN request will be sent with either confirmation or cancellation
		$update_order['transaction_id']  = $response->getTransactionReference(); // a reference generated by the payment gateway
		$update_order['success']         = 'Your transaction is pending review! ' . $response->getMessage();
		$update_order['is_paid']         = 0;
		$update_order['order_completed'] = 0;
		break;
	case 'paid': // transaction is pending authorization. After this is done, a new IPN request will be sent with either confirmation or cancellation
		$update_order['transaction_id']  = $response->getTransactionReference(); // a reference generated by the payment gateway
		$update_order['success']         = 'Your transaction is pending authorization! ' . $response->getMessage();
		$update_order['is_paid']         = 0;
		$update_order['order_completed'] = 0;
		//update DB, SET status = "open/preauthorized"
		break;
	case 'confirmed': // transaction is finalized, the money have been captured from the customer's account
		$update_order['transaction_id']  = $response->getTransactionReference(); // a reference generated by the payment gateway
		$update_order['success']         = 'Your transaction is finalized! ' . $response->getMessage();
		$update_order['is_paid']         = 1;
		$update_order['order_completed'] = 1;
		//update DB, SET status = "confirmed/captured"
		break;
	case 'canceled': // transaction is canceled
		$update_order['transaction_id']  = $response->getTransactionReference(); // a reference generated by the payment gateway
		$update_order['success']         = 'Your transaction is canceled! ' . $response->getMessage();
		$update_order['is_paid']         = 0;
		$update_order['order_completed'] = 0;
		//update DB, SET status = "canceled"

		break;
	case 'credit': // transaction has been refunded
		$update_order['transaction_id']  = $response->getTransactionReference(); // a reference generated by the payment gateway
		$update_order['success']         = 'Your transaction has been refunded! ' . $response->getMessage();
		$update_order['is_paid']         = 0;
		$update_order['order_completed'] = 1;
		//update DB, SET status = "refunded"

		break;
}

$response->sendResponse();

$data['return_to'] = null   ;
 