<?php
use Omnipay\Omnipay;

$merchantId        = get_option( 'mobilpay_merchantid', 'payments' );
$publicCertificate = json_decode( get_option( 'mobilpay_public_certificate', 'payments' ) );
$privateKey        = json_decode( get_option( 'mobilpay_private_key', 'payments' ) );
$testMode          = get_option( 'mobilpay_testmode', 'payments' ) == 1 ? true : false;

$formData = include( dirname( __DIR__ ) . DS . 'lib' . DS . 'omnipay' . DS . 'omnipay_populate_form_data.php' );

/**/
$gateway = Omnipay::create( 'MobilPay' );
$gateway->setMerchantId( $merchantId );
$gateway->setPublicKey( $publicCertificate->path );

try {

	$response = $gateway->purchase( [
		'amount'     => $place_order['amount'],
		'currency'   => 'RON',
		'orderId'    => $place_order['payment_verify_token'],
		'confirmUrl' => $mw_ipn_url,
		'returnUrl'  => $mw_return_url,
		'details'    => $place_order['item_name'],
		'testMode'   => $testMode
	] )->send();

	if ( $response->isSuccessful() ) {
		$place_order['transaction_id']  = $response->getTransactionReference(); // a reference generated by the payment gateway
		$place_order['success']         = 'Your payment was successful! ' . $response->getMessage();
		$place_order['is_paid']         = 1;
		$place_order['order_completed'] = 1;
	} elseif ( $response->isRedirect() ) {
		/*$place_order['order_completed'] = 1;
		$place_order['is_paid']         = 0;
		$place_order['redirect']        = $response->getRedirectUrl();*/

		$place_order['order_completed'] = 1;
		$place_order['is_paid']         = 0;

		$rand = uniqid();
		$form = '<script  type="text/javascript">
					$(document).ready(function(){
					 
					 
					 $("#gateway_form_' . $rand . '").submit();
					
					});
					</script>';

		//error_log(print_R($response->getRedirectData(), true));
		$form .= "<p style=\"text-align:center;\"><h2>Please wait, your order is being processed and you";
		$form .= " will be redirected to the payment website.</h2></p>\n";
		$form .= "<form method=\"POST\" name=\"gateway_form\" id='gateway_form_{$rand}' ";
		$form .= "action=\"" . $response->getRedirectUrl() . "\">\n";

		foreach (  $response->getRedirectData() as $key=>$value ) {
			$form .= "<input type=\"hidden\" name=\"" . $key . "\" value=\"" . $value . "\"/>\n";
		}

		$form .= "<p style=\"text-align:center;\"><br/><br/>If you are not automatically redirected to ";
		$form .= "payment website within 5 seconds...<br/><br/>\n";
		$form .= "<input type=\"submit\" value=\"Click Here\"></p>\n";

		$form .= "</form>\n";

		$place_order['success'] = $form;

		//error_log($form);
		/*error_log(json_encode($response->getRedirectData()));
		error_log(json_encode($response->getRedirectResponse()));*/
	} else {
		$place_order['error'] = $response->getMessage();
	}
} catch ( \Omnipay\Common\Exception\InvalidCreditCardException $e ) {
	$msg = $e->getMessage();

	$place_order['error'] = $msg;
} catch ( \Exception $e ) {
	$msg                  = $e->getMessage();
	$place_order['error'] = $msg;
}